### PR TITLE
fix(ui): minor bug in card buttons

### PR DESCRIPTION
**Pull request by MahendraBishnoi29**
resolves issue #73

### CODE REVIEW

**Comment by nishantwrp** [comment]
Can you post a before/after screenshot please?

**Comment by MahendraBishnoi29** [comment]
> Can you post a before/after screenshot please?

sure @nishantwrp 

before my changes
before

after my changes
after

**Comment by MahendraBishnoi29** [comment]
@nishantwrp ?

**Review by nishantwrp — APPROVED** [review]
lgtm, thanks @MahendraBishnoi29!

**Pull request merged**
