### PR TITLE
added_discord_server_link_of_liquid_galaxy

### PR DESCRIPTION
**Pull request by SagittariusA11**

### CODE REVIEW

**Review by nishantwrp — APPROVED** [review]

**Comment by nishantwrp** [comment]
Thanks, but I hope you know that this feature is not implemented.

**Comment by SagittariusA11** [comment]
Why is it so?

**Comment by nishantwrp** [comment]
@SagittariusA11 Because I'm finding it hard to find the time to do so. If you're interested in implementing this, let me know.

**Comment by SagittariusA11** [comment]
Let me go through the code base. Then will see what can I do.

**Pull request merged**
