### PR TITLE
Feature added: Star organizations (1)

### PR DESCRIPTION
**Pull request by fuushyn**

### CODE REVIEW

**Comment by fuushyn** [comment]
do let me know if you feel the need for any changes @nishantwrp

**Comment by nishantwrp** [comment]
Hi @fuushyn, Thanks for the pull request! I'm out this week. Will review next week.

**Comment by fuushyn** [comment]
Cool!

**Comment by singlamohit1** [comment]
@nishantwrp

**Review by nishantwrp — CHANGES_REQUESTED** [review]
Hi @fuushyn, nice work. Here are a couple of things that need to be addressed before we merge this.

- CI checks are failing
- When I star any organization, the count doesn't change.
- Stars should be renamed to bookmarks
- View stars button should probably be in the sidebar.
- The styling of `Star` button in each organization card should be improved.
- If an organization is already stared, the button text should be changed to "Unstar" ("Remove from bookmarks")

**Comment by beingnoble03** [comment]
This PR can be closed as the issue is being fixed by #94.

**Pull request closed without merging**
